### ISSUE TITLE
Error in fetching the title.

### ISSUE THREAD

**Issue by n00b007** [amrrs/Google-Play-Store-Review-Extractor#3]
On executing the code, after setting the path for the chromedriver, selenium is unable to grab the title and an exception is thrown.

**Comment by amrrs** [comment]
You might have to try this https://github.com/amrrs/google-play-scraper-js

**Comment by amrrs** [comment]
Hope that worked! Closing this!

**Comment by n00b007** [comment]
Yep it worked thanks :+1:

**Comment by amrrs** [comment]
@n00b007 Thanks for the update

**Comment by amrrs** [comment]
@n00b007 Just curious where re you planning to use this

**Comment by n00b007** [comment]
Hey., sorry for the late reply. I am using this + kafka + spark to create a live sentiment analysis for a given app from the app store. So the output instead of the text file will be streamed to a kafka broker and consumed by spark since this is only for one topic. Ideally each topic can be a separate broker and each with its own consumer.
