### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by Leothi** [amrrs/Google-Play-Store-Review-Extractor#4]
Hello!

I tried to use your scrapper and it doesnt work anymore. I guess they changed the tags you use to search with Selenium.

**Comment by amrrs** [comment]
You can use this https://github.com/amrrs/google-play-scraper-js @Leothi

**Comment by Leothi** [comment]
Thanks. 
I've implemented mine with python.
If you want to check it out:
https://github.com/Leothi/Google_Play_app_review_scrapper
